DECLARE 
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE HOSPITALS(H_ID NUMBER(10) PRIMARY KEY, H_NAME VARCHAR(30), H_CITY VARCHAR(30))';
    EXECUTE IMMEDIATE 'CREATE TABLE MEDICINE(MED_CODE NUMBER(10) PRIMARY KEY, MED_PRICE NUMBER(10,2), MED_STOCK NUMBER(10))';
    EXECUTE IMMEDIATE 'CREATE TABLE HOSPITAL_ROOM(H_ID NUMBER(10), ROOM_NO NUMBER(5), BILL_ID NUMBER(10) PRIMARY KEY, TYPE_OF_WARD VARCHAR(20), PRICE NUMBER(10,2), NO_OF_DAYS NUMBER(5), BEDS NUMBER(5), FOREIGN KEY (H_ID) REFERENCES HOSPITALS(H_ID))';
    EXECUTE IMMEDIATE 'CREATE TABLE MED_BILL(BILL_ID NUMBER(10), MED_CODE NUMBER(10), MED_QTY NUMBER(10), PRIMARY KEY(BILL_ID,MED_CODE), FOREIGN KEY (MED_CODE) REFERENCES MEDICINE(MED_CODE), FOREIGN KEY (BILL_ID) REFERENCES HOSPITAL_ROOM(BILL_ID))';
    EXECUTE IMMEDIATE 'CREATE TABLE DOCTORS(DOC_ID NUMBER(10) PRIMARY KEY, DOC_NAME VARCHAR(30), DOC_SALARY NUMBER(10,2), DOC_DEPT VARCHAR(20), H_ID NUMBER(10), FOREIGN KEY (H_ID) REFERENCES HOSPITALS(H_ID))';
    EXECUTE IMMEDIATE 'CREATE TABLE DOCTORS_MOB(DOC_ID NUMBER(10), FOREIGN KEY (DOC_ID) REFERENCES DOCTORS(DOC_ID), DOC_MOB NUMBER(10))';
    EXECUTE IMMEDIATE 'CREATE TABLE DOCTORS_EMAILID(DOC_ID NUMBER(10), FOREIGN KEY (DOC_ID) REFERENCES DOCTORS(DOC_ID), DOC_EMAIL VARCHAR(50))';
    EXECUTE IMMEDIATE 'CREATE TABLE EMPLOYEE(EMP_ID NUMBER(10) PRIMARY KEY, EMP_NAME VARCHAR(20), EMP_TYPE VARCHAR(15), EMP_SALARY NUMBER(10,2), H_ID NUMBER(10), FOREIGN KEY (H_ID) REFERENCES HOSPITALS(H_ID))';
    EXECUTE IMMEDIATE 'CREATE TABLE EMPLOYEE_MOB(EMP_ID NUMBER(10), FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID), EMP_MOB NUMBER(10))';
    EXECUTE IMMEDIATE 'CREATE TABLE PATIENTS(P_ID NUMBER(10) PRIMARY KEY, P_NAME VARCHAR(20), P_DOB DATE, P_SEX VARCHAR(10), P_BLOOD VARCHAR(5), P_ADD VARCHAR(100), H_ID NUMBER(10), DOC_ID NUMBER(10), FOREIGN KEY (DOC_ID) REFERENCES DOCTORS(DOC_ID), BILL_ID NUMBER(10), FOREIGN KEY (BILL_ID) REFERENCES HOSPITAL_ROOM(BILL_ID), FOREIGN KEY (H_ID) REFERENCES HOSPITALS(H_ID), CONSTRAINT CHECK_GENDER CHECK (P_SEX IN (''FEMALE'', ''MALE'', ''OTHER'')))';
    EXECUTE IMMEDIATE 'CREATE TABLE PATIENTS_MOB(P_ID NUMBER(10), FOREIGN KEY (P_ID) REFERENCES PATIENTS(P_ID), P_MOB NUMBER(10))';
END;

CREATE OR REPLACE PROCEDURE ADDHOSP(H_ID IN NUMBER, H_NAME IN VARCHAR, H_CITY IN VARCHAR)
IS
BEGIN
    INSERT INTO HOSPITALS VALUES(H_ID, H_NAME, H_CITY);
END ADDHOSP;

DECLARE
    hos_id HOSPITALS.H_ID%type;
    hos_name HOSPITALS.H_NAME%type;
    hos_city HOSPITALS.H_CITY%type;
BEGIN
    hos_id:=&hos_id;
    hos_name:='&hos_name';
    hos_city:='&hos_city';
    ADDHOSP(hos_id,hos_name,hos_city);
END;

CREATE OR REPLACE PROCEDURE ADDMED(MED_CODE IN VARCHAR, MED_PRICE IN NUMBER, MED_STOCK IN NUMBER)
IS
BEGIN
    INSERT INTO MEDICINE VALUES(MED_CODE, MED_PRICE, MED_STOCK);
END ADDMED;

DECLARE
    med_price MEDICINE.MED_PRICE%type;
    med_code MEDICINE.MED_CODE%type;
    med_stock MEDICINE.MED_STOCK%type;
BEGIN
    med_code:=&med_code;
    med_price:=&med_price;
    med_stock:=&med_stock;
    ADDMED(med_code,med_price,med_stock);
END;

CREATE OR REPLACE PROCEDURE ADDMEDBILL(BILL_ID IN NUMBER, MED_CODE IN NUMBER, MED_QTY IN NUMBER)
IS
BEGIN
    INSERT INTO MED_BILL VALUES(BILL_ID, MED_CODE, MED_QTY);
END ADDMEDBILL;

DECLARE
    bill_id MED_BILL.BILL_ID%type;
    med_code MED_BILL.MED_CODE%type;
    med_qty MED_BILL.MED_QTY%type;
BEGIN
    bill_id:=&bill_id;
    med_code:=&med_code;
    med_qty:=&med_qty;
    ADDMEDBILL(bill_id,med_price,med_qty);
END;

CREATE OR REPLACE PROCEDURE ADDHOSPROOM(H_ID IN NUMBER, ROOM_NO IN NUMBER, BILL_ID IN NUMBER, TYPE_OF_WARD IN VARCHAR, PRICE IN NUMBER, NO_OF_DAYS IN NUMBER, BEDS IN NUMBER)
IS
BEGIN
    INSERT INTO HOSPITAL_ROOM VALUES(H_ID,ROOM_NO,BILL_ID, TYPE_OF_WARD, PRICE,NO_OF_DAYS,BEDS);
END ADDHOSPROOM;

DECLARE
    h_id HOSPITAL_ROOM.H_ID%type;
    room_no HOSPITAL_ROOM.ROOM_NO%type;
    bill_id HOSPITAL_ROOM.BILL_ID%type;
    type_ward HOSPITAL_ROOM.TYPE_OF_WARD%type;
    price HOSPITAL_ROOM.ROOM_PRICE%type;
    no_of_days HOSPITAL_ROOM.NO_OF_DAY%type;
    beds HOSPITAL_ROOM.BEDS%type;
    
BEGIN
    h_id :=&h_id;
    room_no:=&room_no;
    bill_id:=&bill_id;
    type_ward:='&type_ward';
    price:=&r_price;
    no_of_days:=&no_of_days;
    beds:=&beds;
    
    ADDHOSPROOM(h_id,room_no,bill_id,type_ward,price,no_of_days,beds);
END;

CREATE OR REPLACE PROCEDURE ADDDOC(DOC_ID IN NUMBER, DOC_NAME IN VARCHAR, DOC_SALARY IN NUMBER, DOC_DEPT IN VARCHAR, H_ID IN NUMBER)
IS
BEGIN
    INSERT INTO DOCTORS VALUES(DOC_ID, DOC_NAME, DOC_SALARY, DOC_DEPT, H_ID);
END ADDDOC;

DECLARE
    d_id DOCTORS.DOC_ID%type;
    d_name DOCTORS.DOC_NAME%type;
    d_salary DOCTORS.DOC_SALARY%type;
    d_dept DOCTORS.DOC_DEPT%type;
    h_id DOCTOR.H_ID%type;
    
BEGIN
    d_id:=&d_id;
    d_name:='&d_name';
    d_salary:=&d_salary;
    d_dept:='&d_dept';
    h_id:=&h_id;

    ADDDOC(d_id,d_name,d_salary,d_dept,h_id);
END;

CREATE OR REPLACE PROCEDURE ADDDOC_MOB(DOC_ID IN NUMBER, DOC_MOB IN NUMBER)
IS
BEGIN
    INSERT INTO DOCTORS_MOB VALUES(DOC_ID, DOC_MOB);
END ADDDOC_MOB;

DECLARE
    d_id DOCTORS_MOB.DOC_ID%type;
    d_mob DOCTOR_MOB.DOC_MOB%type;
    
BEGIN
    d_id:=&d_id;
    d_mob:=&d_mob;

    ADDDOC_MOB(d_id,d_mob);
END;

CREATE OR REPLACE PROCEDURE ADDDOC_EMAILID(DOC_ID IN NUMBER, DOC_EMAILID IN VARCHAR)
IS
BEGIN
    INSERT INTO DOCTORS_EMAILID VALUES(DOC_ID, DOC_EMAILID);
END ADDDOC_EMAILID;

DECLARE
    d_id DOCTORS_EMAILID.DOC_ID%type;
    d_mob DOCTOR_EMAILID.DOC_EMAILID%type;
    
BEGIN
    d_id:=&d_id;
    d_emailid:='&d_emailid';

    ADDDOC_EMAILID(d_id,d_emailid);
END;

CREATE OR REPLACE PROCEDURE ADDEMP(EMP_ID IN NUMBER, EMP_NAME IN VARCHAR, EMP_SALARY IN NUMBER, EMP_TYPE IN VARCHAR, H_ID IN NUMBER)
IS
BEGIN
    INSERT INTO EMPLOYEE VALUES(EMP_ID, EMP_NAME, EMP_SALARY, EMP_TYPE, H_ID);
END ADDEMP;

DECLARE
    e_id EMPLOYEE.EMP_ID%type;
    e_name EMPLOYEE.EMP_NAME%type;
    e_salary EMPLOYEE.EMP_SALARY%type;
    e_type EMPLOYEE.EMP_TYPE%type;
    h_id EMPLOYEE.H_ID%type;
    
BEGIN
    e_id:=&e_id;
    e_name:='&e_name';
    e_salary:=&e_salary;
    e_type:='&e_type';
    h_id:=&h_id;

    ADDEMP(e_id,e_name,e_salary,e_type,h_id);
END;

CREATE OR REPLACE PROCEDURE ADDEMP_MOB(EMP_ID IN NUMBER, EMP_MOB IN NUMBER)
IS
BEGIN
    INSERT INTO EMPLOYEE_MOB VALUES(EMP_ID, EMP_MOB);
END ADDEMP_MOB;

DECLARE
    e_id EMPLOYEE_MOB.EMP_ID%type;
    e_mob EMPLOYEE_MOB.EMP_MOB%type;
    
BEGIN
    e_id:=&e_id;
    e_mob:=&e_mob;

    ADDEMP_MOB(e_id,e_mob);
END;